name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '30 0 * * *' # 6 am IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Deploy Playwright Report to GitHub Pages
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports/playwright-report

    - name: Zip Playwright report
      if: ${{ always() }}
      run: |
        if [ -d "reports/playwright-report" ]; then
          zip -r playwright-report.zip reports/playwright-report
        fi

    # ✅ Upload report to GitHub Actions
    - name: Upload Playwright Report Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report.zip
        retention-days: 7

    - name: Send Playwright Report Email
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Playwright Test Report
        to: pranayamishra1997@gmail.com
        from: GitHub CI
        body: |
          Hello,
          Playwright tests have completed.
          Please find the report attached.
        attachments: playwright-report.zip
