name: Playwright Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 0 * * *' # 6 AM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Start timer
    - name: Start Timer
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Run Playwright tests
      run: npx playwright test

    # End timer
    - name: End Timer
      if: always()
      run: |
        END_TIME=$(date +%s)
        DURATION=$((END_TIME-START_TIME))
        echo "DURATION=${DURATION}s" >> $GITHUB_ENV

    - name: Extract Test Summary
      if: always()
      run: |
        TOTAL=$(jq '.stats.expected + .stats.unexpected + .stats.skipped' reports/test-results.json)
        PASSED=$(jq '.stats.expected' reports/test-results.json)
        FAILED=$(jq '.stats.unexpected' reports/test-results.json)

        echo "TOTAL=$TOTAL" >> $GITHUB_ENV
        echo "PASSED=$PASSED" >> $GITHUB_ENV
        echo "FAILED=$FAILED" >> $GITHUB_ENV

        if [ "$FAILED" -gt 0 ]; then
          SUBJECT="🔴 $PASSED Passed | $FAILED Failed | Playwright CI"
        else
          SUBJECT="🟢 $PASSED Passed | $FAILED Failed | Playwright CI"
        fi

        echo "EMAIL_SUBJECT=$SUBJECT" >> $GITHUB_ENV

    - name: Generate Allure Report
      if: always()
      run: |
        npx allure generate allure-results --clean -o allure-report

    # Prepare GitHub Pages content
    - name: Prepare Pages Content
      if: always()
      run: |
        rm -rf public
        mkdir -p public
        cp -r reports/playwright-report public/playwright
        mkdir -p public/allure
        cp -r allure-report/* public/allure

    # Deploy reports
    - name: Deploy Reports to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages

    # Zip Playwright report
    - name: Zip Playwright report
      if: always()
      run: |
        zip -r playwright-report.zip reports/playwright-report

    - name: Upload Playwright Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report.zip
        retention-days: 7

    - name: Send Playwright Report Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ env.EMAIL_SUBJECT }}
        to: pranayamishra1997@gmail.com
        from: GitHub CI
        body: |
          Hello,

          The Playwright test execution has completed.

          Total Tests : ${{ env.TOTAL }}
          Passed      : ${{ env.PASSED }}
          Failed      : ${{ env.FAILED }}
          Duration    : ${{ env.DURATION }}

          Playwright HTML Report:
          https://pranaya1997.github.io/Playwright-Framework/playwright/

          Allure Dashboard:
          https://pranaya1997.github.io/Playwright-Framework/allure/

          The Playwright report is also attached as a ZIP file.

          Regards
          GitHub CI Pipeline
        attachments: playwright-report.zip
